apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: toucan-go 
  janus-idp.io/tekton: toucan-go
  backstage.io/kubernetes-id: toucan-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: toucan-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  